[tool.ruff]
line-length = 119

[tool.ruff.lint]
fixable = ["ALL"]
select = ["ALL"]
ignore = [
  "COM819",
  "ANN204",
  "D100",
  "D101",
  "D102",
  "D103",
  "D104",
  "D105",
  "D106",
  "D107",
  "FA102",
  "RUF001",  # ambiguous-unicode-character-string
  "RUF002",  # ambiguous-unicode-character-string
  "PERF203", # try-except-in-loop
  "LOG015",  # using global logger
  "TRY003",
  "EM101",
]

[tool.ruff.lint.per-file-ignores]
"**/migrations/*.py" = ["ALL"]
"manage.py" = ["ALL"]
"**/views.py" = [
  "A002", # builtin-argument-shadowing
]

"**/test_*.py" = [
  "ANN201",
  "PT027",   # self.assertRaises
  "PLR2004", # Magic value used in comparison
  "PT004",
  "S101",    # assert find
  "SLF001",  # Private member accessed
  "DTZ001",  # `datetime.datetime()` called without a `tzinfo` arg
  "FBT001" # Boolean-typed positional argument in function definition
]

"**/scripts/*.py" = [
  "T203", # pprint
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"